# Generated by Django 3.0.7 on 2021-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rollno', models.CharField(max_length=20, unique=True)),
                ('College', models.CharField(choices=[('anits', 'anits'), ('vvit', 'vvit'), ('iiit', 'iiit')], max_length=10)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10)),
            ],
        ),
    ]
